---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/sonarqube/src/main/fabric8/icon.svg"
  labels:
  name: "sonarqube"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "sonarqube"
  template:
    metadata:
      labels:
        name: "sonarqube"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_MASTER"
          value: "https://kubernetes.default"
        image: fabric8/sonarqube:${sonarqube.version}
        name: "sonarqube"
        ports:
        - containerPort: 9000
          name: "sonaqube"
        resources:
         limits:
          cpu: 0.5
          memory: 512M
        requests:
          cpu: 0.5
          memory: 512M
        volumeMounts:
        - mountPath: /opt/sonarqube/config/
          name: sonarqube
      volumes:
      - configMap:
          defaultMode: 420
          name: sonarqube
        name: sonarqube
        items:
        - key: sonar.properties
          path: sonar.properties