---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    expose: "true"
  name: "taiga"
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    provider: "fabric8"
    project: "taiga"
