---
apiVersion: "v1"
data:
  admin-user-create: "true"
  admin-user-email: "gogsadmin@fabric8.local"
  admin-user-name: "gogsadmin"
  admin-user-password: "RedHat$1"
  gogs-oauth--enabled: "true"
  gogs-oauth-openshift--auth-url: ""
  gogs-oauth-openshift--client-id: "gogs"
  gogs-oauth-openshift--enabled: "true"
  gogs-oauth-openshift--scopes: ""
  gogs-oauth-openshift--token-url: ""
  gogs-oauth-twitter--enabled: "false"
  gogs-server--root-url: ""
  gogs-webhook--skip-tls-verify: "true"
  gogs-webhook--task-interval: "true"
  kubernetes-admin-user: "admin"
kind: "ConfigMap"
metadata:
  annotations:
    fabric8.gogs/summary: "[Gogs](http://gogs/) - A self-hosted Git service written\
      \ in Go"
    description: "Gogs is a self-hosted Git service written in Go.\n\nMore details\
      \ on the <a href=\"http://gogs.io/\" target=\"gogs\">Gogs home page</a>.\n"
    fabric8.gogs/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png"
    expose.config.fabric8.io/url-key: "gogs-server--root-url"
    expose.config.fabric8.io/oauth-authorize-url-key: oauth-authorize-uri
    fabric8.io/json-schema: "{\n  \"type\" : \"object\",\n  \"properties\" : {\n \
      \   \"GOGS_SERVER__ROOT_URL\" : {\n      \"type\" : \"string\",\n      \"description\"\
      \ : \"The root URL for the gogs server\"\n    },\n    \"DOMAIN\" : {\n     \
      \ \"type\" : \"string\",\n      \"description\" : \"The domain name applications\
      \ are installed on\",\n      \"default\" : \"vagrant.f8\"\n    },\n    \"ADMIN_USER_EMAIL\"\
      \ : {\n      \"type\" : \"string\",\n      \"description\" : \"The email address\
      \ of the admin user on Gogs\",\n      \"default\" : \"gogsadmin@fabric8.local\"\
      \n    },\n    \"ADMIN_USER_PASSWORD\" : {\n      \"type\" : \"string\",\n  \
      \    \"description\" : \"The password to login to Gogs\",\n      \"default\"\
      \ : \"RedHat$1\"\n    },\n    \"GOGS_SERVER__PROTOCOL\" : {\n      \"type\"\
      \ : \"string\",\n      \"description\" : \"The protocol for gogs to use; either\
      \ http or https\",\n      \"default\" : \"http\"\n    },\n    \"GOGS_OAUTH_OPENSHIFT__ENABLED\"\
      \ : {\n      \"type\" : \"string\",\n      \"default\" : \"true\"\n    },\n\
      \    \"ADMIN_USER_CREATE\" : {\n      \"type\" : \"string\",\n      \"description\"\
      \ : \"Should we create an admin user on startup\",\n      \"default\" : \"true\"\
      \n    },\n    \"GOGS_OAUTH_OPENSHIFT__TOKEN_URL\" : {\n      \"type\" : \"string\"\
      \n    },\n    \"GOGS_OAUTH_OPENSHIFT__SCOPES\" : {\n      \"type\" : \"string\"\
      \n    },\n    \"GOGS_OAUTH_OPENSHIFT__AUTH_URL\" : {\n      \"type\" : \"string\"\
      \n    },\n    \"GOGS_WEBHOOK__TASK_INTERVAL\" : {\n      \"type\" : \"string\"\
      ,\n      \"default\" : \"true\"\n    },\n    \"GOGS_WEBHOOK__SKIP_TLS_VERIFY\"\
      \ : {\n      \"type\" : \"string\",\n      \"default\" : \"true\"\n    },\n\
      \    \"GOGS_SERVER__DOMAIN\" : {\n      \"type\" : \"string\",\n      \"description\"\
      \ : \"The gogs server name\",\n      \"default\" : \"gogs.vagrant.f8\"\n   \
      \ },\n    \"ADMIN_USER_NAME\" : {\n      \"type\" : \"string\",\n      \"description\"\
      \ : \"The user name to login to Gogs\",\n      \"default\" : \"gogsadmin\"\n\
      \    },\n    \"GOGS_OAUTH__ENABLED\" : {\n      \"type\" : \"string\",\n   \
      \   \"default\" : \"true\"\n    },\n    \"GOGS_OAUTH_TWITTER__ENABLED\" : {\n\
      \      \"type\" : \"string\",\n      \"default\" : \"false\"\n    },\n    \"\
      KUBERNETES_ADMIN_USER\" : {\n      \"type\" : \"string\",\n      \"description\"\
      \ : \"The default Kubernetes admin user\",\n      \"default\" : \"admin\"\n\
      \    },\n    \"GOGS_OAUTH_OPENSHIFT__CLIENT_ID\" : {\n      \"type\" : \"string\"\
      ,\n      \"default\" : \"gogs\"\n    }\n  }\n}"
  labels: {}
  name: "gogs"
