---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/gogs/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
    expose: "true"
  name: "gogs-ssh"
spec:
  ports:
  - port: 22
    protocol: "TCP"
    targetPort: 2222
  selector:
    project: "gogs"
    provider: "fabric8"
    group: "io.fabric8.devops.apps"
