---
apiVersion: "v1"
data:
  chaos-monkey-kill-frequency-seconds: "60"
  chaos-monkey-excludes: "letschat*,gogs*"
  chaos-monkey-room: "#fabric8_${namespace}"
  chaos-monkey-includes: "*"
kind: "ConfigMap"
metadata:
  annotations:
    fabric8.chaos-monkey/summary: "Kills random pods for chaos fun!"
    description: "Randomly kills pods to help check your environment can withstand\
      \ failures"
    fabric8.chaos-monkey/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/chaos-monkey/src/main/fabric8/icon.png"
    fabric8.io/json-schema: "{\n  \"type\" : \"object\",\n  \"properties\" : {\n \
      \   \"CHAOS_MONKEY_INCLUDES\" : {\n      \"type\" : \"string\",\n      \"description\"\
      \ : \"Comma separated list of patterns for pods which should be considered for\
      \ deletion\",\n      \"default\" : \"*\"\n    },\n    \"CHAOS_MONKEY_EXCLUDES\"\
      \ : {\n      \"type\" : \"string\",\n      \"description\" : \"Comma separated\
      \ list of patterns for pods which should not be deleted\",\n      \"default\"\
      \ : \"letschat*,gogs*\"\n    },\n    \"CHAOS_MONKEY_ROOM\" : {\n      \"type\"\
      \ : \"string\",\n      \"description\" : \"The chat room to talk to\",\n   \
      \   \"default\" : \"#fabric8_${namespace}\"\n    },\n    \"CHAOS_MONKEY_KILL_FREQUENCY_SECONDS\"\
      \ : {\n      \"type\" : \"string\",\n      \"description\" : \"The number of\
      \ seconds between a kill\",\n      \"default\" : \"60\"\n    }\n  }\n}"
  labels: {}
  name: "chaos-monkey"
