---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/manageiq/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
    expose: "true"
  name: "manageiq"
spec:
  ports:
  - port: 443
    protocol: "TCP"
    targetPort: 443
  selector:
    project: "manageiq"
    provider: "fabric8"
    group: "io.fabric8.devops.apps"
