---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    project: "${project.artifactId}"
    provider: "fabric8"
    expose: "true"
  name: "jenkins"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "jenkins"
    provider: "fabric8"
