---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-letschat/src/main/fabric8/icon.png"
    fabric8.io/app-menu: development
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
    expose: "true"
  name: "hubot"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "hubot-letschat"
    provider: "fabric8"
    group: "io.fabric8.devops.apps"
