---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "letschat"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    expose: "true"
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    name: "letschat"
