---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/content-repository/src/main/fabric8/icon.svg"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
    expose: "true"
  name: "content-repository"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 80
  selector:
    project: "content-repository"
    provider: "fabric8"
    group: "io.fabric8.devops.apps"
